name: CD - Client

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
      VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
      VERCEL_PROJECT_ID: '${{ secrets.VERCEL_PROJECT_ID }}'

    steps:
      - name: Check Vercel Token
        if: env.VERCEL_TOKEN == ''
        run: |
          echo 'You are missing the VERCEL_TOKEN secret!'
          exit 1

      - name: Check Vercel Org ID
        if: env.VERCEL_ORG_ID == ''
        run: |
          echo 'You are missing the VERCEL_ORG_ID secret!'
          exit 1

      - name: Check Vercel Project ID
        if: env.VERCEL_PROJECT_ID == ''
        run: |
          echo 'You are missing the VERCEL_PROJECT_ID secret!'
          exit 1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          github-token: '${{ secrets.GH_BOT_TOKEN }}'
          vercel-token: '${{ secrets.VERCEL_TOKEN }}'
          vercel-org-id: '${{ secrets.VERCEL_ORG_ID }}'
          vercel-project-id: '${{ secrets.VERCEL_PROJECT_ID }}'
          vercel-args: '--prod'
          github-comment: true
