name: Release Please

on:
  push:
    branches:
      - 'master'

jobs:
  release-please:
    name: 'Run'
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          command: manifest
          monorepo-tags: true
